### ISSUE TITLE
Deprecate the mrt package?

### ISSUE THREAD

**Issue by dandv** [peerlibrary/meteor-pdf.js#16]
Sorry if I filed this elsewhere, but can't find it now. https://atmospherejs.com/mrt/pdf.js seems like an older version of https://atmospherejs.com/peerlibrary/pdf.js.

**Comment by mitar** [comment]
Yes. How can I do that? When I do `meteor search pdf.js` I get only new version.

**Comment by dandv** [comment]
Interesting. https://atmospherejs.com/?q=pdf does show `mrt:pdfjs`. Try:

```
meteor admin set-unmigrated mrt:pdfjs
```

Also, to remove `mrt` as a contributor:

```
meteor admin maintainers mrt:pdfjs --remove mrt
```

If you were originally the maintainer on the old package system, you can attach your Meteor Developer account at http://atmosphere.meteor.com/accounts, then ping tmeasday to give you ownership of the old package.

**Comment by mitar** [comment]
I already did all this quite some time ago. This is why it does not show in `meteor search`. I am not sure what is with Atmosphere.

**Comment by tmeasday** [comment]
@dandv I don't see it? http://cl.ly/image/1v0z0R2O0a2h

**Comment by mitar** [comment]
Hm, interesting. I also do not see it anymore. Maybe some of commands I was rerunning above did in fact change something. I am closing this ticket.
